# Generated by Django 3.0.7 on 2021-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lista',
            name='data_evento',
            field=models.DateTimeField(),
        ),
    ]
